common: &common
  adapter: mysql2
  username: root
  host: localhost

etl_execution:
  <<: *common
  database: aw_etl_sample_etl_execution

datawarehouse:
  <<: *common
  database: aw_etl_sample_datawarehouse
  encoding: utf8
  local_infile: true