common: &common
  adapter: mysql
  username: root
  host: localhost

etl_execution:
  <<: *common
  database: aw_etl_sample_etl_execution

datawarehouse:
  <<: *common
  database: aw_etl_sample_datawarehouse
